### ISSUE TITLE
Mech_midi

### ISSUE THREAD

**Issue by goog** [anvit/cm-storm-switch-tester-mod#1]
like music, and I'm very curious about it. need a midi software or some hardware? could you describe it in detail please? thx

**Comment by anvit** [comment]
Hi @goog, not sure if I understand your question. This would work with any software that supports midi(which includes all major Digital Audio Workstations), however this isn't intended to be a proper midi device  since 6 keys is too less to be used in any real scenario. If you still want to see how I went about building it, you can follow the link in the readme, and refer to the circuit diagram here to get an idea.
